[book]
authors = ["Success Kingsley"]
language = "en"
src = "./"
title = "The NaijaScript Interpreter"

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/xosnrdev/naijascript"
edit-url-template = "https://github.com/xosnrdev/naijascript/edit/docs/{path}"
